[package]
name = "susy-codec"
description = "Lightweight, efficient, binary serialization and deserialization codec"
version = "3.5.0"
authors = ["Susy Technologies <admin@superstring.ch>"]
license = "Apache-2.0"
repository = "https://github.com/susytech/susy-codec"
categories = ["encoding"]
edition = "2018"

[dependencies]
arrayvec = { version = "0.4", default-features = false }
serde = { version = "1.0", optional = true }
susy-codec-derive = { path = "derive", version = "3.3", default-features = false, optional = true }

[dev-dependencies]
serde_derive = { version = "1.0" }
susy-codec-derive = { path = "derive", version = "3.3", default-features = false }

[features]
default = ["std"]
derive = ["susy-codec-derive"]
std = ["serde"]

# WARNING: DO _NOT_ USE THIS FEATURE IF YOU ARE WORKING ON CONSENSUS CODE!*
#
# Provides implementations for more data structures than just Vec and Box.
# Concretely it will provide susy-codec implementations for many types
# that can be found in std and/or alloc (nightly).
#
# This feature was mainly introduced after it became clear that pDSL requires
# it for the sake of usability of its users.
#
# * For rational about this please visit:
# https://github.com/susytech/susy-codec/pull/27#issuecomment-453031914
full = []

[workspace]
members = [
	"derive",
]
